### ISSUE TITLE
Why not use LiveData transformation?

### ISSUE THREAD

**Issue by eugenebrusov** [bakkenbaeck/android-mvvm#4]
Seems like on this line 

https://github.com/bakkenbaeck/android-mvvm/blob/1baf462a01ab5889be17327a8f89c914f056a916/app/src/main/java/com/bakkenbaeck/mvvm/ui/comments/CommentsViewModel.kt#L12

you do something like it was marked as "// DON'T DO THIS" on this section https://developer.android.com/topic/libraries/architecture/livedata.html#transform_livedata.

With your current approach, the UI component needs to unregister from the previous LiveData object and register to the new instance each time it calls `CommentsViewModel.comments`. In addition, if the UI component is recreated, it triggers another call to the `commentsRepo.getComments()` method instead of using the previous call’s result.

My guess `Transformations.switchMap` might bring much more seamless behaviour.

**Comment by csdodd** [comment]
`commentsRepo.getComments()` returns a `LiveData` that is stored in the value `comments`. When the view is rotated, it is destroyed but the ViewModel is not; nor is `comments` destroyed. So when the view reattaches after rotate, it will reattach to the same LiveData.

The documentation you are referring to is slightly different because an argument (`address`) is being passed into the ViewModel. This means a new LiveData is being returned for each `address` that is passed in -- which as the documentation points out, is a problem because the view needs to keep unregistering and registering to different LiveData instances. In that example, Transformations are used to always return the same LiveData.
